FROM scratch
ADD rootfs/opt/ /
RUN sed -i 's/^mirrorlist/#mirrorlist/; s/^#baseurl/baseurl/; s/download.fedoraproject.org\/pub/localhost/' \
	/etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo

# Clean up stale rpmdb path inside installroot (/opt/var/lib/rpm) from bdb temporary cache/lock files.
# Without this, rpm will fail with an error because the stale path does not exist inside the installroot.
RUN rm -f /var/lib/rpm/__db.00*
RUN rpm --rebuilddb
